name: Generate Snake Animation

on:
  # Executa a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite executar manualmente a partir da aba Actions
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para a action escrever no repositório
      
    steps:
      - name: Generate snake animation
        # Esta é a ÚNICA action que você precisa
        uses: Platane/snk@v3
        with:
          # Seu nome de usuário do GitHub (pega automaticamente)
          github_user_name: ${{ github.repository_owner }}
          
          # Lista de arquivos a serem gerados
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        
        env:
          # O token de acesso do GitHub é necessário para salvar o arquivo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
